export enum AffiliationEnum {
  JUSTICE_LEAGUE = 1,
  BAT_FAMILY,
  AVENGERS,
  FANTASTIC_FOUR,
  ILLUMINATI,
  DEFENDERS,
  X_MEN,
  SHIELD,
  GREEN_LANTERN_CORPS,
  GUARDIANS_OF_THE_GALAXY,
  UNKNOWN,
}
